export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER'
}

export enum Permission {
  VIEW_BOOKINGS = 'VIEW_BOOKINGS',
  CREATE_BOOKING = 'CREATE_BOOKING',
  MODIFY_BOOKING = 'MODIFY_BOOKING',
  DELETE_BOOKING = 'DELETE_BOOKING',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',
  MANAGE_HOTELS = 'MANAGE_HOTELS',
  MANAGE_FLIGHTS = 'MANAGE_FLIGHTS',
  MANAGE_CARS = 'MANAGE_CARS',
  MANAGE_PACKAGES = 'MANAGE_PACKAGES',
  MANAGE_ACTIVITIES = 'MANAGE_ACTIVITIES',
  MANAGE_TRANSPORTATION = 'MANAGE_TRANSPORTATION',
  MANAGE_EVENTS = 'MANAGE_EVENTS',
  MANAGE_PROMOTIONS = 'MANAGE_PROMOTIONS'
}

export type PermissionMap = {
  [key in UserRole]: Permission[];
};

export const DEFAULT_PERMISSIONS: PermissionMap = {
  ADMIN: Object.values(Permission),
  USER: [
    Permission.VIEW_BOOKINGS,
    Permission.CREATE_BOOKING
  ]
}; 